package main

import (
	"github.com/komuw/dbscan/heart"
)

/*
usage:
  go run -race heart/cmd/main.go
*/

func main() {
	heart.Run(6, 2, []float64{1, 2, 2, 2, 2, 3, 8, 7, 8, 8, 25, 80}, 3.0, 1.0, false, "testHeartRun")

	/*
			or if you want Data to be autogenerated for you
		heart.Run(6, 2, []float64{1, 2, 2, 2, 2, 3, 8, 7, 8, 8, 25, 80}, 3.0, 1.0, true)
	*/
}
